# Generated by Django 4.0.4 on 2022-06-01 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addhook',
            options={'verbose_name_plural': 'Hooks'},
        ),
        migrations.AlterModelOptions(
            name='addneedle',
            options={'verbose_name_plural': 'Needles'},
        ),
        migrations.AlterModelOptions(
            name='addyarndetailed',
            options={'verbose_name_plural': 'Yarn'},
        ),
        migrations.AddField(
            model_name='addhook',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addneedle',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addyarndetailed',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
