# Generated by Django 4.0.4 on 2022-06-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0002_alter_addhook_options_alter_addneedle_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addyarndetailed',
            old_name='brand',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='addyarndetailed',
            name='weight',
        ),
        migrations.AddField(
            model_name='addyarndetailed',
            name='yarn_weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
