# Generated by Django 4.0.4 on 2022-06-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0003_rename_brand_addyarndetailed_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addyarndetailed',
            name='yarn_weight',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
