# Generated by Django 4.0.4 on 2022-06-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0004_alter_addyarndetailed_yarn_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addyarndetailed',
            name='colorway',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='addyarndetailed',
            name='fiber_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='addyarndetailed',
            name='notes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='addyarndetailed',
            name='yardage',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='addyarndetailed',
            name='yarn_weight',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
