# Generated by Django 4.0.4 on 2022-06-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0005_alter_addyarndetailed_colorway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addyarndetailed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
