# Generated by Django 4.0.4 on 2022-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0006_addyarndetailed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addyarndetailed',
            name='notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
