# Generated by Django 4.0.4 on 2022-06-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0007_alter_addyarndetailed_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='addyarndetailed',
            name='skeins',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addyarndetailed',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
