# Generated by Django 4.0.4 on 2022-06-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0008_addyarndetailed_skeins_alter_addyarndetailed_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addhook',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addneedle',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addneedle',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
