# Generated by Django 4.0.4 on 2022-06-08 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_data', '0009_alter_addhook_brand_alter_addneedle_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddKnitProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=50)),
                ('designer', models.CharField(blank=True, max_length=50, null=True)),
                ('needles', models.CharField(blank=True, max_length=50, null=True)),
                ('gauge', models.CharField(blank=True, max_length=30, null=True)),
                ('yarn', models.CharField(blank=True, max_length=50, null=True)),
                ('colorway', models.CharField(blank=True, max_length=50, null=True)),
                ('total_yardage', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='AddCrochetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=50)),
                ('designer', models.CharField(blank=True, max_length=50, null=True)),
                ('hook', models.CharField(blank=True, max_length=50, null=True)),
                ('gauge', models.CharField(blank=True, max_length=30, null=True)),
                ('yarn', models.CharField(blank=True, max_length=50, null=True)),
                ('colorway', models.CharField(blank=True, max_length=50, null=True)),
                ('total_yardage', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
