# Generated by Django 4.0.4 on 2022-06-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0014_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddYarnBasic',
        ),
        migrations.AlterField(
            model_name='addhook',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='addneedle',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='pattern_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addyarndetailed',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
